POST http://localhost:3000/api/admin/subcategories HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "name":"SubCategory",
    "parent":"62de404b48e41b5afb638641"
}

################
GET http://localhost:3000/api/admin/subcategories HTTP/1.1
Content-Type: application/json
Content-Type: application/json

###################
GET http://localhost:3000/api/admin/subcategories/62de3df30767ada57edb72e1 HTTP/1.1
Content-Type: application/json
Accept: application/json

###################
PATCH http://localhost:3000/api/admin/subcategories/62de3df30767ada57edb72e1 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name":"sub category 2",
    "parent":"62de3db50767ada57edb72df",
    "description":"Hello world this my updated category"
}

#########################
DELETE http://localhost:3000/api/admin/subcategories/62de3df30767ada57edb72e1 HTTP/1.1
Content-Type: application/json
Accept: application/json
